<form action="index/submit" method="post">
    <div class='text-black bg-white row m-2 p-2'>
        <div class='col-3'><input type="text" name="search" class="form-control" placeholder="search...."></div>
        <div class='col-1 p-2 ms-1'><input type="checkbox" name="albums" class="form-check-input ">album</div>
        <div class='col-1 p-2 ms-1'><input type="checkbox" name="artists" class="form-check-input">artist</div>
        <div class='col-1 p-2 ms-1'><input type="checkbox" name="playlists" class="form-check-input">playlist</div>
        <div class='col-1 p-2 ms-1'><input type="checkbox" name="tracks" class="form-check-input">track</div>
        <div class='col-1 p-2 ms-1'><input type="checkbox" name="shows" class="form-check-input">show</div>
        <div class='col-1 p-2 ms-1'><input type="checkbox" name="episodes" class="form-check-input">episode</div>
        <div class='col-2'><input type="submit" value="submit" name='submit' class='btn btn-primary'></div>
        <div class='col-1'><a href='my' class='btn btn-info'>My</a></div>
    </div>
</form>
